#!/usr/bin/env python3
"""design-scope blueprint — renders the band skeleton the agent fills.

Takes a structure (from get_page_structure, corpus-measured or curated) and
emits a full skeleton page: every band marked data-band/data-band-type,
<meta name="bands"/><meta name="mechanisms"/> matching the structure contract,
the sheet's design language, per-type mechanism scaffolding, and scroll-reveal
wiring by default (IntersectionObserver arms data-band-scroll → the verdict's
fabric floor passes 3/3). Placeholder content carries class="fill" — the
agent's job is copy, SVG, and motion, never the structure.

The skeleton keeps the /*__DATA__*/ and /*__TOKENS_*__*/ markers so
build_showcase.py remains the single injection point.

Usage:
  python scripts/blueprint.py --structure bands.json --out skeleton.html
"""
import argparse
import json
import sys
from pathlib import Path

# ------------------------------------------------------------------ the sheet

SHELL_HEAD = """<!DOCTYPE html>
<!--
  Generated by scripts/blueprint.py — structure from get_page_structure.
  Decisions by the server · rendering by the agent · grading by the server.
  Bands and mechanism budget are the structure contract; the verdict measures
  the rendered document against them.
-->
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="bands" content="{bands}">
<meta name="mechanisms" content="{mechanisms}">
<title>design-scope — one-shotted · SHEET 02</title>
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Crect x='1.5' y='1.5' width='13' height='13' fill='none' stroke='%231E5EFF' stroke-width='2'/%3E%3Cpath d='M4 8h8M8 4v8' stroke='%231E5EFF' stroke-width='1.5'/%3E%3C/svg%3E">
<style>
:root {
/*__TOKENS_LIGHT__*/
}
html[data-theme="dark"] {
/*__TOKENS_DARK__*/
}
* { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; }
body {
  font-family: -apple-system, "Segoe UI", Inter, system-ui, sans-serif;
  background: var(--paper);
  color: var(--ink);
  transition: background-color 0.25s ease, color 0.25s ease;
  -webkit-font-smoothing: antialiased;
}
body::before {
  content: ""; position: fixed; inset: 0; z-index: 0; pointer-events: none;
  background-image:
    repeating-linear-gradient(0deg, var(--grid) 0 1px, transparent 1px 32px),
    repeating-linear-gradient(90deg, var(--grid) 0 1px, transparent 1px 32px);
}
::selection { background: var(--sel); }
a { color: var(--accent-text); text-decoration: none; }
.mono, .lbl, code, pre, .fig-label, .tick-label, .band-tag, .status-tag {
  font-family: ui-monospace, "Cascadia Mono", Consolas, "SF Mono", monospace;
}
.lbl { font-size: 11px; letter-spacing: 0.14em; text-transform: uppercase; color: var(--muted); }
.sheet { position: relative; z-index: 1; max-width: 1180px; margin: 0 auto; padding: 0 40px; }
.band { position: relative; padding: 72px 0 64px; border-top: 1px solid var(--line); }
.nav {
  position: sticky; top: 0; z-index: 50; background: var(--paper);
  border-bottom: 1px solid var(--line); transition: background-color 0.25s ease;
}
.nav-inner { max-width: 1180px; margin: 0 auto; padding: 14px 40px; display: flex; align-items: center; gap: 26px; }
.brand { display: flex; align-items: center; gap: 10px; font-weight: 700; font-size: 15px; letter-spacing: -0.01em; }
.brand-mark { width: 18px; height: 18px; }
.brand-mark rect, .brand-mark path { fill: none; stroke: var(--accent); stroke-width: 1.8; }
.nav-links { display: flex; gap: 18px; margin-left: 8px; }
.nav-links a {
  font-size: 12px; letter-spacing: 0.08em; color: var(--muted); position: relative; padding: 3px 0;
  transition: color 0.18s ease;
}
.nav-links a::after {
  content: ""; position: absolute; left: 0; bottom: -1px; height: 1px; width: 0;
  background: var(--accent); transition: width 0.22s cubic-bezier(0.19, 1, 0.22, 1);
}
.nav-links a:hover { color: var(--ink); }
.nav-links a:hover::after { width: 100%; }
.nav-right { margin-left: auto; display: flex; align-items: center; gap: 16px; }
.status-dot {
  width: 7px; height: 7px; border-radius: 50%; background: var(--pass);
  animation: dot-pulse 2.6s ease-in-out infinite;
}
.status-tag { display: flex; align-items: center; gap: 7px; font-size: 10px; letter-spacing: 0.14em; color: var(--muted); }
.theme-btn {
  display: inline-flex; align-items: center; justify-content: center; width: 30px; height: 30px;
  border: 1px solid var(--line); border-radius: 4px; background: transparent; color: var(--ink); cursor: pointer;
  transition: border-color 0.18s ease, background-color 0.18s ease, transform 0.18s ease;
}
.theme-btn:hover { border-color: var(--accent); transform: translateY(-1px); }
.theme-btn svg { width: 14px; height: 14px; fill: none; stroke: currentColor; stroke-width: 1.6; }
.theme-btn .sun { display: none; }
html[data-theme="dark"] .theme-btn .sun { display: block; }
html[data-theme="dark"] .theme-btn .moon { display: none; }
.cta {
  display: inline-block; padding: 9px 18px; border-radius: 4px; font-size: 13px; font-weight: 600;
  letter-spacing: 0.02em; transition: transform 0.18s cubic-bezier(0.19, 1, 0.22, 1), box-shadow 0.18s ease;
}
.cta-primary { background: var(--accent); color: var(--on-accent); box-shadow: 0 1px 0 var(--shadow); }
.cta-primary:hover { transform: translateY(-1px); box-shadow: 0 2px 8px var(--shadow); }
.cta-ghost { border: 1px solid var(--line); color: var(--ink); background: transparent; }
.cta-ghost:hover { border-color: var(--accent); color: var(--accent-text); transform: translateY(-1px); }
.hero { padding: 96px 0 88px; display: grid; grid-template-columns: 1.02fr 0.98fr; gap: 48px; align-items: center; }
.kicker { display: flex; align-items: center; gap: 12px; margin-bottom: 22px; }
.kicker::before { content: ""; width: 26px; height: 1px; background: var(--accent); }
.h1 { font-size: 62px; line-height: 1.02; letter-spacing: -0.03em; font-weight: 800; margin-bottom: 22px; }
.h1 .rule { display: block; margin-top: 14px; width: 148px; }
.h1 .rule path { stroke: var(--accent); stroke-width: 1.5; fill: none; }
.h1 .rule .ticks { stroke: var(--accent-line); }
.sub { font-size: 17.5px; line-height: 1.75; color: var(--muted); max-width: 46ch; margin-bottom: 30px; }
.claim {
  font-size: 11.5px; letter-spacing: 0.1em; text-transform: uppercase; color: var(--muted);
  border-left: 3px solid var(--accent); padding: 10px 14px; margin-bottom: 30px; background: var(--sel); line-height: 1.7;
}
.claim b { color: var(--accent-text); }
.cta-row { display: flex; gap: 12px; margin-bottom: 40px; }
.ticker {
  display: grid; grid-template-columns: repeat(4, auto); gap: 8px 26px; justify-content: start;
  border: 1px solid var(--line); border-radius: 4px; padding: 14px 18px; background: var(--card);
}
.ticker span { font-size: 10.5px; letter-spacing: 0.12em; color: var(--muted); text-transform: uppercase; white-space: nowrap; }
.ticker b { color: var(--ink); font-weight: 700; }
.fig { border: 1px solid var(--line); background: var(--card); border-radius: 6px; padding: 18px 18px 14px; box-shadow: 0 1px 0 var(--shadow); }
.fig-head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 14px; }
.fig-label { font-size: 10px; letter-spacing: 0.14em; color: var(--muted); text-transform: uppercase; }
.fig-live { display: flex; gap: 5px; }
.fig-live i { width: 6px; height: 6px; border-radius: 50%; background: var(--line); }
.fig-live i:nth-child(1) { background: var(--under); }
.band-head { display: flex; align-items: baseline; gap: 18px; margin-bottom: 40px; }
.band-num { font-size: 13px; color: var(--accent-text); font-weight: 700; letter-spacing: 0.1em; }
.band-tag { font-size: 11px; letter-spacing: 0.14em; color: var(--muted); text-transform: uppercase; }
.band-title { font-size: 34px; font-weight: 800; letter-spacing: -0.02em; margin-top: 10px; }
.band-intro { font-size: 15px; line-height: 1.6; color: var(--muted); max-width: 62ch; margin-top: 10px; }
.divider { display: block; width: 100%; margin-top: 26px; }
.divider line { stroke: var(--line); stroke-width: 1; }
.divider .tick { stroke: var(--line); stroke-width: 1; }
.divider .center { stroke: var(--accent); stroke-width: 1.2; }
.stat-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }
.stat-card {
  background: var(--card); border: 1px solid var(--line); border-radius: 6px; padding: 22px 20px 18px;
  box-shadow: 0 1px 0 var(--shadow); transition: border-color 0.18s ease, transform 0.18s cubic-bezier(0.19, 1, 0.22, 1);
}
.stat-card:hover { border-color: var(--accent-line); transform: translateY(-1px); }
.stat-num { font-size: 40px; font-weight: 800; letter-spacing: -0.03em; line-height: 1; }
.stat-num .unit { font-size: 16px; color: var(--muted); font-weight: 600; margin-left: 4px; letter-spacing: 0; }
.stat-label { margin-top: 10px; font-size: 12px; letter-spacing: 0.1em; text-transform: uppercase; color: var(--muted); }
.stat-note { margin-top: 6px; font-size: 13px; line-height: 1.5; color: var(--muted); }
.tool-table { width: 100%; border-collapse: collapse; margin-top: 8px; }
.tool-table th {
  text-align: left; font-size: 10px; letter-spacing: 0.14em; text-transform: uppercase; color: var(--muted);
  font-weight: 600; padding: 8px 12px; border-bottom: 1px solid var(--line);
}
.tool-table td { padding: 11px 12px; border-bottom: 1px solid var(--line); font-size: 13.5px; vertical-align: top; }
.tool-table tbody tr { transition: background-color 0.15s ease; }
.tool-table tbody tr:hover { background: var(--sel); }
.tool-table code { font-size: 12.5px; color: var(--accent-text); }
.tool-table td.desc { color: var(--muted); line-height: 1.5; }
.verdict-score { display: flex; align-items: center; gap: 26px; margin-bottom: 26px; flex-wrap: wrap; }
.score-big { font-size: 44px; font-weight: 800; letter-spacing: -0.03em; }
.score-meta { font-size: 12px; color: var(--muted); letter-spacing: 0.06em; line-height: 1.7; }
.rubric, .ledger { width: 100%; border-collapse: collapse; }
.rubric th, .ledger th {
  text-align: left; font-size: 10px; letter-spacing: 0.14em; text-transform: uppercase; color: var(--muted);
  font-weight: 600; padding: 8px 12px; border-bottom: 1px solid var(--line);
}
.rubric td, .ledger td { padding: 13px 12px; border-bottom: 1px solid var(--line); font-size: 13.5px; vertical-align: top; }
.rubric td.group, .ledger td.group { font-size: 10px; letter-spacing: 0.14em; color: var(--muted); white-space: nowrap; padding-top: 16px; }
.rubric td.detail { color: var(--muted); line-height: 1.5; }
.rubric tbody tr, .ledger tbody tr { transition: background-color 0.15s ease; }
.rubric tbody tr:hover, .ledger tbody tr:hover { background: var(--sel); }
.badge {
  display: inline-block; padding: 3px 10px; border-radius: 3px; font-size: 11px; font-weight: 700;
  letter-spacing: 0.1em; border: 1px solid currentColor;
}
.badge.PASS { color: var(--pass); }
.badge.UNDER { color: var(--under); }
.verdict-caption {
  margin-top: 16px; font-size: 10px; letter-spacing: 0.12em; color: var(--muted); text-transform: uppercase; line-height: 1.8;
}
.verdict-pending, .ledger-empty { border: 1px dashed var(--line); padding: 30px; text-align: center; color: var(--muted); font-size: 13.5px; }
.scan-cols { display: grid; grid-template-columns: 1.05fr 0.95fr; gap: 40px; align-items: start; }
.scan-block h3 { font-size: 12px; letter-spacing: 0.14em; text-transform: uppercase; color: var(--muted); margin-bottom: 18px; font-weight: 600; }
.bar-row { display: grid; grid-template-columns: 110px 1fr 34px; align-items: center; gap: 12px; margin-bottom: 10px; }
.bar-label { font-size: 12px; color: var(--muted); text-align: right; letter-spacing: 0.04em; }
.bar-track { height: 16px; background: var(--track); border: 1px solid var(--line); border-radius: 3px; position: relative; }
.bar-fill { height: 100%; background: var(--accent-soft); border-right: 1.5px solid var(--accent); transition: width 0.5s cubic-bezier(0.19, 1, 0.22, 1); }
.bar-count { font-size: 12px; font-weight: 700; font-variant-numeric: tabular-nums; }
.scan-insight {
  margin-top: 28px; padding: 18px 20px; border: 1px solid var(--line); border-left: 3px solid var(--accent);
  background: var(--card); font-size: 14px; line-height: 1.65; color: var(--muted);
}
.steps { display: grid; grid-template-columns: 250px 1fr; gap: 0; border: 1px solid var(--line); border-radius: 6px; overflow: hidden; background: var(--card); }
.step-list { border-right: 1px solid var(--line); }
.step {
  display: block; width: 100%; text-align: left; padding: 14px 18px; cursor: pointer; background: transparent;
  border: 0; border-bottom: 1px solid var(--line); font-size: 13px; letter-spacing: 0.03em; color: var(--muted);
  position: relative; transition: color 0.15s ease, background-color 0.15s ease;
  font-family: ui-monospace, "Cascadia Mono", Consolas, monospace;
}
.step:last-child { border-bottom: 0; }
.step .n { color: var(--accent-text); font-weight: 700; margin-right: 8px; }
.step:hover { color: var(--ink); background: var(--sel); }
.step:hover .n { color: var(--accent-text); }
.step.active { color: var(--on-accent); background: var(--accent); font-weight: 700; }
.step.active .n { color: var(--on-accent); }
.step.active::before { content: ""; position: absolute; left: 0; top: 0; bottom: 0; width: 2px; background: var(--on-accent); }
.step-detail { padding: 26px 28px; display: flex; flex-direction: column; justify-content: center; min-height: 260px; }
.step-detail .d-label { font-size: 10px; letter-spacing: 0.14em; text-transform: uppercase; color: var(--accent-text); margin-bottom: 10px; }
.step-detail p { font-size: 14.5px; line-height: 1.7; color: var(--muted); word-break: break-word; }
.step-detail code { font-size: 12.5px; color: var(--ink); }
.register-note {
  margin-top: 18px; font-size: 10px; letter-spacing: 0.12em; color: var(--muted); text-transform: uppercase; line-height: 1.8;
}
.cmd-list { display: grid; gap: 12px; margin-top: 8px; }
.cmd {
  display: flex; align-items: center; gap: 14px; background: var(--card); border: 1px solid var(--line);
  border-radius: 6px; padding: 14px 16px;
}
.cmd .arrow { color: var(--accent-text); font-weight: 700; }
.cmd code { font-size: 13px; color: var(--ink); }
.cmd .note { margin-left: auto; font-size: 11px; letter-spacing: 0.08em; color: var(--muted); text-transform: uppercase; }
.copy-btn {
  flex-shrink: 0; padding: 6px 12px; font-size: 11px; letter-spacing: 0.1em; text-transform: uppercase;
  border: 1px solid var(--line); border-radius: 4px; background: transparent; color: var(--muted); cursor: pointer;
  transition: border-color 0.15s ease, color 0.15s ease; font-family: ui-monospace, "Cascadia Mono", Consolas, monospace;
}
.copy-btn:hover { border-color: var(--accent); color: var(--accent-text); }
.copy-btn.copied { border-color: var(--pass); color: var(--pass); }
.start-note { margin-top: 20px; font-size: 12px; letter-spacing: 0.1em; color: var(--muted); text-transform: uppercase; }
.footer {
  border-top: 1px solid var(--line); margin-top: 40px; padding: 26px 0 30px;
  display: flex; align-items: center; gap: 24px; flex-wrap: wrap;
}
.footer .end-tag { font-size: 10px; letter-spacing: 0.14em; color: var(--muted); text-transform: uppercase; }
.footer .status-tag { margin-left: auto; }
.fill { outline: 1px dashed var(--accent-line); outline-offset: 6px; }
.fill-tag {
  display: inline-block; font-size: 9px; letter-spacing: 0.14em; color: var(--accent-text);
  border: 1px solid var(--accent-line); border-radius: 3px; padding: 2px 6px; margin-bottom: 10px; text-transform: uppercase;
}
@keyframes dot-pulse {
  0%, 100% { opacity: 1; transform: scale(1); }
  50% { opacity: 0.35; transform: scale(0.82); }
}
@keyframes draw { to { stroke-dashoffset: 0; } }
@keyframes band-in {
  from { opacity: 0; transform: translateY(10px); }
  to { opacity: 1; transform: translateY(0); }
}
@keyframes fade-in { from { opacity: 0; } to { opacity: 1; } }
/* scroll-gated reveal: bands start hidden only when JS is present (the .js
   class is added before first paint), then animate when .revealed lands —
   previously .band animated at load and .revealed was a no-op */
.js .band { opacity: 0; }
.js .band.revealed { animation: band-in 0.6s cubic-bezier(0.19, 1, 0.22, 1) both; }
.band:nth-of-type(2) { animation-delay: 0.08s; }
.band:nth-of-type(3) { animation-delay: 0.16s; }
.band:nth-of-type(4) { animation-delay: 0.24s; }
.band:nth-of-type(5) { animation-delay: 0.32s; }
.band:nth-of-type(6) { animation-delay: 0.4s; }
.band:nth-of-type(7) { animation-delay: 0.48s; }
.band:nth-of-type(8) { animation-delay: 0.56s; }
.band:nth-of-type(9) { animation-delay: 0.64s; }
.hero .h1 { animation: band-in 0.55s cubic-bezier(0.19, 1, 0.22, 1) 0.05s both; }
.hero .sub { animation: band-in 0.55s cubic-bezier(0.19, 1, 0.22, 1) 0.15s both; }
.hero .cta-row { animation: band-in 0.55s cubic-bezier(0.19, 1, 0.22, 1) 0.25s both; }
.fig { animation: band-in 0.6s cubic-bezier(0.19, 1, 0.22, 1) 0.35s both; }
  .ledger td .dots { letter-spacing: 2px; font-size: 10px; }
  .vh { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0 0 0 0); white-space: nowrap; }
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.001s !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.001s !important;
  }
  html { scroll-behavior: auto; }
}
</style>
<script>
/* restore theme BEFORE first paint — no light flash for dark users */
(function () { try {
  var t = localStorage.getItem("ds-theme");
  if (!t && window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches) t = "dark";
  if (t) document.documentElement.setAttribute("data-theme", t);
} catch (e) {} })();
</script>
</head>
<body>
"""

SHELL_FOOT = """
<script>
/*__DATA__*/
document.documentElement.classList.add("js");  // gates scroll-reveal CSS
(function () {
  "use strict";
  var S = window.SHOWCASE || { stats: null, verdict: null, ledger: [], oneShot: null };
  var OS = S.oneShot;

  function renderStats() {
    if (!S.stats) return;
    document.querySelectorAll('[data-stat]').forEach(function (el) {
      var key = el.getAttribute('data-stat');
      var v = key.split('.').reduce(function (o, k) { return o ? o[k] : null; }, S.stats);
      if (v !== null && v !== undefined) el.textContent = v;
    });
  }
  function bars(containerId, rows, max) {
    var el = document.getElementById(containerId);
    if (!el || !rows.length) return;
    var html = "";
    rows.forEach(function (r) {
      var w = Math.round((r[1] / max) * 100);
      html += '<div class="bar-row"><span class="bar-label">' + r[0] + '</span>' +
        '<div class="bar-track"><div class="bar-fill" style="width:' + w + '%"></div></div>' +
        '<span class="bar-count">' + r[1] + '</span></div>';
    });
    el.innerHTML = html;
  }
  function renderScan() {
    if (!S.stats) return;
    var st = S.stats.styles;
    var arch = (st.top_archetypes || []).slice(0, 6);
    var hues = (st.top_hues || []).slice(0, 6);
    bars("arch-bars", arch, arch.length ? arch[0][1] : 1);
    bars("hue-bars", hues, hues.length ? hues[0][1] : 1);
    var total = S.stats.corpus.style_indexed || 1;
    var insight = document.getElementById("scan-insight");
    if (insight && arch.length) {
      var top = arch[0], share = Math.max(1, Math.round(total / top[1]));
      insight.textContent = top[0] + " leads the index at " + top[1] + " of " + total +
        " — one in " + share + " cards. " + S.stats.corpus.dark_themed +
        " cards ship a dark palette (" + Math.round(100 * S.stats.corpus.dark_themed / total) +
        "%), and the one-shot picked among them.";
    }
  }
  function renderReference() {
    var el = document.getElementById("ref-line");
    if (!el || !OS || !OS.card) return;
    var why = (OS.card.why || "").slice(0, 260);
    el.innerHTML = 'REFERENCE — <code>' + OS.card.slug + '</code> · borrowed for the palette on this sheet ' +
      (OS.direction ? 'via <code>style_search("' + OS.direction + '")</code> · ' : '') +
      (why ? 'why: <em>' + why + '</em>…' : '');
  }
  function badge(status) { return '<span class="badge ' + status + '">' + status + '</span>'; }
  function renderVerdict() {
    var root = document.getElementById("verdict-root");
    if (!root) return;
    if (!S.verdict) {
      root.innerHTML = '<div class="verdict-pending">PENDING — run scripts/verdict.py on this page.</div>';
      return;
    }
    var v = S.verdict, rows = "";
    v.checks.forEach(function (c) {
      rows += '<tr><td class="group">' + c.group + '</td><td><strong>' + c.name + '</strong></td>' +
        '<td class="detail">' + c.detail + '</td><td>' + badge(c.status) + '</td></tr>';
    });
    var d = new Date(v.date);
    root.innerHTML =
      '<div class="verdict-score"><div class="score-big">' + v.summary.pass + ' PASS · ' + v.summary.under + ' UNDER</div>' +
      '<div class="score-meta">LABEL <strong>' + (v.label || "—") + '</strong><br>READ OFF THE PRODUCTION BUILD AT 1440×900 ON ' +
      (d.toISOString ? d.toISOString().slice(0, 10) : v.date).toUpperCase() + '</div></div>' +
      '<table class="rubric"><thead><tr><th style="width:110px">group</th><th style="width:220px">check</th><th>evidence</th><th style="width:90px">status</th></tr></thead>' +
      '<tbody>' + rows + '</tbody></table>' +
      '<div class="verdict-caption">STRUCTURAL FIGURES COUNTED FROM THE RENDERED DOCUMENT — NOT FROM THE RECORD THAT PLANNED IT · ' +
      v.summary.total + ' OF ' + v.summary.total + ' CHECKS · ' + v.summary.score + '</div>';
  }
  function renderLedger() {
    var root = document.getElementById("ledger-root");
    if (!root) return;
    if (!S.ledger || !S.ledger.length) {
      root.innerHTML = '<div class="ledger-empty">NO ROWS YET — THE FIRST VERDICT IS THE ONE ABOUT TO BE WRITTEN.</div>';
      return;
    }
    var rows = "", all = S.ledger.slice().reverse();
    all.forEach(function (r, i) {
      var dots = "", npass = 0;
      (r.rows || []).forEach(function (c) {
        if (c.status === "PASS") npass++;
        dots += c.status === "PASS" ? '<span style="color:var(--pass)">●</span>'
                                    : '<span style="color:var(--under)">○</span>';
      });
      var under = (r.rows || []).length - npass;
      // row number from the record's own label when it carries one — position-
      // based numbering once disagreed with the labels under "no row is edited"
      var m = /R(\\d+)/i.exec(r.label || "");
      var rn = m ? m[1] : String(all.length - i);
      rows += '<tr><td class="group" style="color:var(--muted)">R' + rn.padStart(2, "0") + '</td>' +
        '<td><strong>' + (r.label || "—") + '</strong></td><td>' + (r.date || "").slice(0, 10) + '</td>' +
        '<td>' + r.score + '</td><td class="dots" aria-label="' + npass + ' pass, ' + under + ' under">' +
        dots + '<span class="vh">' + npass + ' pass, ' + under + ' under</span></td></tr>';
    });
    root.innerHTML =
      '<table class="ledger"><thead><tr><th style="width:60px">row</th><th>label</th><th style="width:110px">date</th>' +
      '<th style="width:150px">score</th><th>checks</th></tr></thead><tbody>' + rows + '</tbody></table>' +
      '<div class="verdict-caption">' + S.ledger.length + ' ROWS · OLDEST AT THE FOOT · NO ROW IS EVER EDITED AFTER IT LANDS</div>';
  }
  function renderRegister() {
    var list = document.getElementById("step-list");
    var label = document.getElementById("step-label");
    var text = document.getElementById("step-text");
    var note = document.getElementById("register-note");
    if (!list) return;
    if (!OS || !OS.register || !OS.register.length) return;
    var entries = OS.register, steps = [];
    function esc(s) { return s.replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]; }); }
    function showEntry(e) {
      label.textContent = (e.stage || "").toUpperCase() + " · " + e.tool;
      var inp = typeof e.input === "string" ? e.input : JSON.stringify(e.input);
      var out = typeof e.output === "string" ? e.output : JSON.stringify(e.output);
      text.innerHTML = "<strong>IN</strong> <code>" + esc(inp) + "</code><br><br>" +
        "<strong>OUT</strong> <code>" + esc(out) + "</code>" +
        (e.ts ? "<br><br><span style='font-size:11px'>" + e.ts + "</span>" : "");
    }
    entries.forEach(function (e, i) {
      var btn = document.createElement("button");
      btn.className = "step" + (i === 0 ? " active" : "");
      btn.innerHTML = '<span class="n">' + String(i + 1).padStart(2, "0") + "</span>" + e.tool;
      list.appendChild(btn);
      steps.push(btn);
      btn.addEventListener("click", function () {
        steps.forEach(function (x) { x.classList.remove("active"); });
        btn.classList.add("active");
        showEntry(e);
      });
    });
    showEntry(entries[0]);
    if (note) note.textContent = "SPENT " + (typeof OS.credits === "number" ? OS.credits : 0) +
      " CREDITS" + (OS.credits_note ? " · " + OS.credits_note : "") + " · " + entries.length +
      " CALLS · EVERY ROW MACHINE-WRITTEN";
  }
  function wireMechanisms() {
    var btn = document.getElementById("themeBtn");
    if (btn) {
      var setPressed = function () {
        btn.setAttribute("aria-pressed",
          document.documentElement.getAttribute("data-theme") === "dark" ? "true" : "false");
      };
      btn.addEventListener("click", function () {
        var next = document.documentElement.getAttribute("data-theme") === "dark" ? "light" : "dark";
        document.documentElement.setAttribute("data-theme", next);
        try { localStorage.setItem("ds-theme", next); } catch (e) {}
        setPressed();
      });
      // saved choice wins; otherwise honor the OS preference (dark users used
      // to get a light page plus a flash on every load)
      try {
        var saved = localStorage.getItem("ds-theme");
        if (!saved && window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches) {
          saved = "dark";
        }
        if (saved) document.documentElement.setAttribute("data-theme", saved);
      } catch (e) {}
      setPressed();
    }
    document.querySelectorAll(".copy-btn").forEach(function (b) {
      b.addEventListener("click", function () {
        var txt = b.getAttribute("data-copy") || "";
        var done = function () {
          b.textContent = "copied"; b.classList.add("copied");
          setTimeout(function () { b.textContent = "copy"; b.classList.remove("copied"); }, 1600);
        };
        if (navigator.clipboard && navigator.clipboard.writeText) navigator.clipboard.writeText(txt).then(done, done);
        else { var ta = document.createElement("textarea"); ta.value = txt; document.body.appendChild(ta); ta.select();
               try { document.execCommand("copy"); } catch (e) {} document.body.removeChild(ta); done(); }
      });
    });
    document.querySelectorAll('[data-step-list]').forEach(function (list) {
      var label = document.getElementById(list.getAttribute("data-step-label"));
      var text = document.getElementById(list.getAttribute("data-step-text"));
      var steps = list.querySelectorAll(".step");
      steps.forEach(function (s) {
        s.addEventListener("click", function () {
          steps.forEach(function (x) { x.classList.remove("active"); });
          s.classList.add("active");
          if (label) label.textContent = s.getAttribute("data-title") || "";
          if (text) text.textContent = s.getAttribute("data-detail") || "";
        });
      });
      if (steps[0]) steps[0].classList.add("active");
    });
    // arm every declared mechanism band
    document.querySelectorAll('[data-band][data-mechanism]').forEach(function (b) {
      var armed = b.hasAttribute("data-interactive") || b.querySelector(".theme-btn, .copy-btn, .step") !== null;
      if (armed) b.setAttribute("data-armed", "");
    });
  }
  function wireScrollReveal() {
    var reduce = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    var bands = document.querySelectorAll("[data-band-scroll]");
    if (reduce || !bands.length) {
      bands.forEach(function (b) { b.setAttribute("data-scroll-armed", ""); b.classList.add("revealed"); });
      return;
    }
    // arm bands in view NOW (synchronous — IO's first callback is async and
    // environment-dependent; the verdict measures at 2.5s)
    var inView = function (b) {
      var r = b.getBoundingClientRect();
      return r.top < window.innerHeight && r.bottom > 0;
    };
    var pending = [];
    bands.forEach(function (b) {
      if (inView(b)) {
        b.setAttribute("data-scroll-armed", "");
        b.classList.add("revealed");
      } else {
        pending.push(b);
      }
    });
    if (!pending.length) return;
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (en) {
        if (en.isIntersecting) {
          en.target.setAttribute("data-scroll-armed", "");
          en.target.classList.add("revealed");
          io.unobserve(en.target);
        }
      });
    }, { rootMargin: "0px 0px -10% 0px" });
    pending.forEach(function (b) { io.observe(b); });
  }
  renderStats(); renderScan(); renderReference(); renderVerdict(); renderLedger(); renderRegister();
  wireMechanisms(); wireScrollReveal();
})();
</script>
</body>
</html>
"""

# ------------------------------------------------------------------ band bodies

def _head(num: str, tag: str, title: str, intro: str, corpus: dict | None = None) -> str:
    c = ""
    if corpus and corpus.get("measured"):
        c = (f'<span class="lbl" style="display:block;margin-top:8px">'
             f'MEASURED {corpus["measured"]} · {corpus["with_state"]} HOLD STATE · '
             f'{int(round(corpus["share"] * 100))}%</span>')
    elif corpus is not None:
        c = ('<span class="lbl" style="display:block;margin-top:8px">'
             'MEASURED 0 — THE CORPUS HAS NOT SEEN THIS BAND TYPE YET</span>')
    return (f'<div class="band-head"><span class="band-num">{num}</span>'
            f'<span class="band-tag">{tag}</span>'
            f'<div><h2 class="band-title">{title}</h2>'
            f'<p class="band-intro">{intro}</p>{c}</div></div>'
            f'<svg class="divider" viewBox="0 0 1100 8" aria-hidden="true"><line x1="0" y1="4" x2="1100" y2="4"/>'
            f'<path class="tick" d="M20 1v6M40 1v6M60 1v6M80 1v6"/><path class="center" d="M1040 1v6M1060 1v6M1080 1v6"/></svg>')


def band_nav(i: int, corpus: dict | None = None, c: dict | None = None) -> str:
    links = (c or {}).get("links") or '<span class="fill-tag">NAV LINKS — AGENT FILLS</span>'
    return f'''<nav class="nav" id="s{i:02d}" data-band="nav" data-band-type="nav" data-mechanism data-band-scroll aria-label="Site">
  <div class="nav-inner">
    <div class="brand">
      <svg class="brand-mark" viewBox="0 0 18 18" aria-hidden="true"><rect x="1.5" y="1.5" width="15" height="15"/><path d="M4.5 9h9M9 4.5v9"/></svg>
      design-scope
    </div>
    <div class="nav-links">{links}</div>
    <div class="nav-right">
      <span class="status-tag"><i class="status-dot" aria-hidden="true"></i>OPERATIONAL</span>
      <button id="themeBtn" class="theme-btn" aria-label="Toggle theme" aria-pressed="false">
        <svg class="sun" viewBox="0 0 16 16" aria-hidden="true"><circle cx="8" cy="8" r="3.2"/><path d="M8 1v2M8 13v2M1 8h2M13 8h2M2.8 2.8l1.4 1.4M11.8 11.8l1.4 1.4M13.2 2.8l-1.4 1.4M4.2 11.8l-1.4 1.4"/></svg>
        <svg class="moon" viewBox="0 0 16 16" aria-hidden="true"><path d="M13.2 9.6A5.6 5.6 0 0 1 6.4 2.8a5.6 5.6 0 1 0 6.8 6.8z"/></svg>
      </button>
      <a class="cta cta-primary" href="#s01">GET STARTED</a>
    </div>
  </div>
</nav>'''


def band_hero(i: int, corpus: dict | None = None, c: dict | None = None) -> str:
    c = c or {}
    headline = c.get("headline") or "HEADLINE — AGENT FILLS"
    sub = c.get("sub") or "Sub — agent fills: what the page is, in one breath."
    cta_p = c.get("cta_primary") or '<a class="cta cta-primary" href="#s02">PRIMARY CTA — AGENT FILLS</a>'
    cta_s = c.get("cta_secondary") or '<a class="cta cta-ghost" href="#s03">SECONDARY CTA — AGENT FILLS</a>'
    fig = c.get("fig") or ('<div class="fill" style="min-height:220px;padding:12px">'
                           '<span class="fill-tag">FIG ART — AGENT FILLS (SVG)</span></div>')
    return f'''<section class="band" id="s{i:02d}" data-band="hero" data-band-type="hero" data-mechanism data-interactive data-band-scroll>
  <div class="hero">
    <div>
      <div class="kicker"><span class="lbl">[ SHEET 02 / ONE-SHOT ]</span></div>
      <h1 class="h1">{headline}
        <svg class="rule" viewBox="0 0 148 12" aria-hidden="true"><path d="M0 6h118"/><path d="M118 1v10M122 3v6M126 1v10M130 3v6M134 1v10M138 3v6M142 1v10M146 3v6" /></svg>
      </h1>
      <p class="sub">{sub}</p>
      <div class="claim"><b>ONE-SHOTTED WITH DESIGN-SCOPE</b> — decisions by the server · rendering by the agent · grading by the server</div>
      <div class="cta-row">
        {cta_p}
        {cta_s}
      </div>
      <div class="ticker"><span class="lbl">[ SHEET SPEC ]</span>
        <span><b data-stat="corpus.captured">—</b> captured</span>
        <span><b data-stat="corpus.annotated">—</b> vision-reviewed</span>
        <span><b>0</b> credits · local-first</span>
      </div>
    </div>
    <figure class="fig">
      <div class="fig-head"><span class="fig-label">FIG. 01 / THE REGISTER</span><span class="fig-live" aria-hidden="true"><i></i><i></i><i></i></span></div>
      {fig}
    </figure>
  </div>
</section>'''


def band_generic(i: int, t: str, corpus: dict | None = None, mechanism: bool = False,
                 content_html: str | None = None, title: str | None = None,
                 intro: str | None = None) -> str:
    mech = " data-mechanism" if mechanism else ""
    inter = " data-interactive" if mechanism else ""
    if content_html:
        body = content_html
    else:
        body = (f'<div class="fill" style="min-height:160px;padding:12px">'
                f'<span class="fill-tag">CONTENT — AGENT FILLS</span>'
                f'<p style="color:var(--muted);font-size:14px">Copy, media, and any type-specific '
                f'interaction go here. The band, its contract, and its mechanism are already decided.</p></div>')
    head_title = title or f"{t.replace('-', ' ').title()} — AGENT FILLS"
    head_intro = intro or "Intro — agent fills what this band says and why it earns its place."
    return f'''<section class="band" id="s{i:02d}" data-band="{t}" data-band-type="{t}"{mech}{inter} data-band-scroll>
  {_head(str(i).zfill(2), t.upper(), head_title, head_intro, corpus)}
  {body}
</section>'''


def band_footer(i: int, corpus: dict | None = None, c: dict | None = None) -> str:
    return f'''<footer class="footer" data-band="footer" data-band-type="footer" data-band-scroll>
  <span class="end-tag">[ END OF SHEET · ONE-SHOTTED WITH DESIGN-SCOPE · LOCAL-FIRST ]</span>
  <span class="status-tag"><i class="status-dot" aria-hidden="true"></i>OPERATIONAL</span>
</footer>'''


BAND_RENDERERS = {
    "nav": band_nav,
    "hero": band_hero,
    "footer": band_footer,
}


def render(structure: dict, content: dict | None = None) -> str:
    """Skeleton page from a structure (get_page_structure output).

    content: optional per-type fill layer (scripts/sheet_content.py) —
    {type: {"title":..., "intro":..., "body":...}} or {type: "<html>"}.
    """
    content = content or {}
    bands = structure["bands"]
    body = []
    nav_html = ""
    for b in bands:
        t = b["type"]
        c = content.get(t)
        slot = c if isinstance(c, dict) else None
        fn = BAND_RENDERERS.get(t)
        if fn:
            rendered = fn(b["index"], b.get("corpus"), slot)
            if t == "nav":
                # the sticky nav lives OUTSIDE .sheet — inside the 1180px
                # container it stuck with unpainted gutters on wide viewports
                nav_html = rendered
                continue
            body.append(rendered)
        else:
            raw = c if isinstance(c, str) else (slot or {}).get("body")
            body.append(band_generic(b["index"], t, b.get("corpus"), b.get("mechanism"),
                                     raw, (slot or {}).get("title"), (slot or {}).get("intro")))
    html = SHELL_HEAD.replace("{bands}", str(structure["declared_bands"])) \
                     .replace("{mechanisms}", str(structure["mechanism_budget"]))
    html += nav_html + "\n"
    html += '\n<div class="sheet">\n' + "\n".join(body) + "\n</div>\n"
    html += SHELL_FOOT
    return html


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--structure", required=True, help="structure JSON (get_page_structure output)")
    ap.add_argument("--out", default=None, help="output path")
    args = ap.parse_args()
    structure = json.loads(Path(args.structure).read_text(encoding="utf-8"))
    out = render(structure)
    out_path = Path(args.out or "skeleton.html")
    out_path.write_text(out, encoding="utf-8")
    print(f"blueprint -> {out_path} ({structure['declared_bands']} bands · "
          f"mechanism budget {structure['mechanism_budget']})")
    print("  fill placeholders, then grade — structure stays as rendered")


if __name__ == "__main__":
    main()
